<a href="https://colab.research.google.com/github/RMoulla/IYT_Septembre/blob/main/Copie_de_TP_Introduction_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Travaux pratiques : Bases de Python**

## Première commande

In [ ]:
# Première commande : afficher bonjour
print("Bonjour")

Bonjour

## Les différents types de variables

In [ ]:
print(type(4))
print(type(3.14))
print(type("Bonjour"))
print(type(True))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>

## Assignation

In [ ]:
# La variable a prend la valeur 2

entier = 2
print(entier)

2

In [ ]:
# Ajouter 1 à entier

entier + 1

3

In [ ]:
# La variable reel prend la valeur 3

reel = 3.14
print(reel)

3.14

In [ ]:
# Calculer la somme de entier et reel

entier + reel

5.140000000000001

In [ ]:
# Définir bonjour comme une chaîne de caractère

bonjour = "Bonjour"
print(bonjour)

Bonjour

In [ ]:
# Définir alice comme une chaîne de caractère

alice = " Alice"
print(alice)

 Alice

In [ ]:
# Calculer le produit entre entier et bonjour

print(entier*bonjour)

BonjourBonjour

In [ ]:
# La somme de bonjour et alice
print(bonjour+alice)

Bonjour Alice

In [ ]:
# Ecraser la valeur d'une variable

alice = " Bob"
print(bonjour + alice)

Bonjour Bob

In [ ]:
# Variable logique

vrai = True
faux = False
print(vrai)
print(faux)

True
False

In [ ]:
# Somme et produit de deux variables logiques
print(vrai+faux)
print(vrai*faux)

1
0

In [ ]:
# Produit d'une variable logique et d'un nombre

print(vrai*2)
print(faux*2)

2
0

In [ ]:
# Produit d'une variable logique et d'une chaîne de caractère

print(vrai*bonjour)
print(faux*bonjour)

Bonjour

## Les conditions

In [ ]:
# si a est supérieur à 1 afficher "a est supérieur à 1"

a = 2
if a > 1:
   print("a est supérieur à 1")

a est supérieur à 1

In [ ]:
# Si a est supérieur à 3 afficher "à supérieur à 3"
# sinon afficher "a est inférieur ou égal à 3"

if a > 3:
    print("a est supérieur à 3")
else:
    print("a est inférieur ou égal à 3")

a est inférieur ou égal à 3

In [ ]:
# Si a est égal à 2 afficher "a est égal à 2"

if a == 2:
    print("a est égal à 2")

a est égal à 2

In [ ]:
# Condition complexe :
# Si a n'est pas égal à 1
# et si a est inférieur à 3
# afficher a est inférieur à 3

if a != 1 and a < 3:
    print("a est inférieur à 3")

a est inférieur à 3

In [ ]:
# Si a est différent de 1
# ou si a est inférieur 0
# afficher "Bonjour"

if a != 1 or a < 0:
    print("Bonjour")

Bonjour

In [ ]:
# Si a est égal à 1 afficher "a est égal à 1"
# sinon si a est inférieur à 1 afficher "a est inférieur à 1"
# sinon si a est supérieur à 1 afficher "a est supérieur à 1"

if a == 1:
  print("a est égal à 1")
elif a < 1:
  print("a est inférieur à 1")
else:
  print("a est supérieur à 1")

a est supérieur à 1

In [ ]:
# Condition avec une chaîne de caractère

char = "Bonjour"

if char:
  print("La chaîne de caractère n'est pas vide")

La chaîne de caractère n'est pas vide

In [ ]:
# Piège de la condition if sur des valeurs nulles

x = 0

if x:
  print("x a une valeur")
else:
  print("x n'a pas de valeur")

x n'a pas de valeur

## Boucles itératives `for`

In [ ]:
# Boucle for qui calcule les carrés des nombres de ma_liste

ma_liste = [1, 2, 3, 4, 5]

for iterateur in ma_liste:
  print(iterateur**2)

1
4
9
16
25

In [ ]:
# Boucle for avec range

for i in range(1,5):
  print(i)

1
2
3
4

## Les listes

In [ ]:
# Définir une liste

ma_liste = [10, 20, 40, 20, 5]

print(ma_liste)

[10, 20, 40, 20, 5]

In [ ]:
# Accéder au premier élément de la liste

ma_liste[0]

10

In [ ]:
# Accéder au deuxième élément de la liste

ma_liste[1]

20

In [ ]:
# Accéder au dernier élément de la liste

ma_liste[-1]

5

In [ ]:
# Accéder à plusieurs éléments en fonction de l'index

ma_liste[1:3]

[20, 40]

In [ ]:
# Modifier un élément d'une liste

ma_liste[0] = 15
print(ma_liste)

[15, 20, 40, 20, 5]

In [ ]:
# Insérer un élément dans une liste

ma_liste.insert(2, 35)
print(ma_liste)

[15, 20, 35, 40, 20, 5]

In [ ]:
# Ajouter un élément à la dernière position

ma_liste.append(20)
print(ma_liste)

[15, 20, 35, 40, 20, 5, 20]

In [ ]:
# Supprimer un élément d'une liste avec pop

ma_liste.pop(2)
print(ma_liste)

[15, 20, 40, 20, 5, 20]

In [ ]:
# Supprimer l'élément 20

ma_liste.remove(20)
print(ma_liste)

[15, 40, 20, 5, 20]

In [ ]:
# Enlever tous les éléments dont la valeur est 20 de la liste
for i in ma_liste:
  if i == 20:
    ma_liste.remove(i)

print(ma_liste)

[15, 40, 5]

In [ ]:
# Ordonner une liste

ma_liste.sort()
print(ma_liste)

[5, 15, 40]

In [ ]:
# Inverser l'ordre des éléments

ma_liste.reverse()
print(ma_liste)

[40, 15, 5]

In [ ]:
# Ordonner une chaine de caractère

char_list = ["Bob", "Alice", "Gargamel"]
char_list.sort()
print(char_list)

['Alice', 'Bob', 'Gargamel']

In [ ]:
# Ordonner une chaine de caractère selon un critère

char_list.sort(key=len)
print(char_list)

['Bob', 'Alice', 'Gargamel']

In [ ]:
# Ajouter une liste à une liste liste2 existante

ma_liste.extend(char_list)
print(ma_liste)

[40, 15, 5, 'Bob', 'Alice', 'Gargamel']

In [ ]:
# Référence et copie

ma_copie = ma_liste
print(ma_copie)

[40, 15, 5, 'Bob', 'Alice', 'Gargamel']

In [ ]:
# Enlever le dernier élément de ma_copie

ma_copie.pop()
print(ma_copie)

[40, 15, 5, 'Bob', 'Alice']

In [ ]:
print(ma_liste)

[40, 15, 5, 'Bob', 'Alice']

In [ ]:
# Copier une liste avec copy

ma_copie = ma_liste.copy()
print(ma_copie)

[40, 15, 5, 'Bob', 'Alice']

In [ ]:
ma_copie.pop()
print(ma_copie)
print(ma_liste)

[40, 15, 5, 'Bob']
[40, 15, 5, 'Bob', 'Alice']

In [ ]:
# Attention : la copie réalisée avec copie est superficielle

list1 = [1, 2, [3, 4]]
list2 = list1.copy()


list2[2][0] = 5

print(list1)
print(list2)

[1, 2, [5, 4]]
[1, 2, [5, 4]]

In [ ]:
# Copie profonde avec deepcopy

import copy

list1 = [1, 2, [3, 4]]
list2 = copy.deepcopy(list1)

list2[2][0] = 5

print(list1)
print(list2)

[1, 2, [3, 4]]
[1, 2, [5, 4]]

In [ ]:
# Calculer les carrés d'une liste et sauvegarder dans liste_carre

liste_carre = []

for i in range(1000_000):
  liste_carre.append(i**2)

liste_carre [:5]

[0, 1, 4, 9, 16]

In [ ]:
# Calculer les carrés avec une comprehension de liste

liste_carre = [i**2 for i in range(1000_000)]

print(liste_carre[:5])

[0, 1, 4, 9, 16]

In [ ]:
# Parcourir deux listes

liste1 = [1, 2, 3]
liste2 = ["a", "b", "c"]

for i, j in zip(liste1, liste2):
  print(i, j)

1 a
2 b
3 c

In [ ]:
# Parcourir une liste avec enumérate

for i, j in enumerate(liste2):
  print(i, j)

0 a
1 b
2 c

## Les dictionnaires

In [ ]:
# Définir un dictionnaire avec {}

mon_dict = {"Nom" : "Alice", "Age" : 38, "Ville" : "Lyon"}
print(mon_dict)

{'Nom': 'Alice', 'Age': 38, 'Ville': 'Lyon'}

In [ ]:
# Accéder à la valeur de Age

mon_dict["Age"]

38

In [ ]:
# Modifier la valeur de l'âge

mon_dict["Age"] = 39
print(mon_dict)

{'Nom': 'Alice', 'Age': 39, 'Ville': 'Lyon'}

In [ ]:
# Ajouter une clé profession

mon_dict["Profession"] = "Ingénieur"
print(mon_dict)

{'Nom': 'Alice', 'Age': 39, 'Ville': 'Lyon', 'Profession': 'Ingénieur'}

In [ ]:
# Récupérer les clés du dictionnaire

mon_obj = mon_dict.keys()
print(mon_obj)

dict_keys(['Nom', 'Age', 'Ville', 'Profession'])

In [ ]:
# Sauvegarder les clés d'un dictionnaire dans une liste
mes_cles = list(mon_dict.keys())
print(mes_cles)

['Nom', 'Age', 'Ville', 'Profession']

In [ ]:
mes_cles[0]

'Nom'

In [ ]:
# Sauvegarder les valeurs d'un dictionnaire dans une liste
mes_valeurs = list(mon_dict.values())
print(mes_valeurs)

['Alice', 39, 'Lyon', 'Ingénieur']

In [ ]:
# Créer un dictionnaire à partir de deux listes

cles = ["Nom", "Age", "Ville"]
valeurs = ["Bob", 42, "Paris"]

bob_dict = dict(zip(cles, valeurs))
print(bob_dict)

{'Nom': 'Bob', 'Age': 42, 'Ville': 'Paris'}

## Les dataframes

In [ ]:
# Créer un dataframe

import pandas as pd

df = pd.DataFrame(
    {"Nom" : ["Alice", "Bob", "Sophie"],
     "Age" : [39, 42, 25],
     "Ville" : ["Lyon", "Paris", "Lyon"]
    }
    )
df

      Nom  Age  Ville
0   Alice   39   Lyon
1     Bob   42  Paris
2  Sophie   25   Lyon

In [ ]:
# Afficher les noms des colonnes

df.columns

Index(['Nom', 'Age', 'Ville'], dtype='object')

In [ ]:
# Afficher la dimension du dataframe
df.shape

(3, 3)

In [ ]:
# Afficher les valeurs de la colonne Nom

df['Nom']

0     Alice
1       Bob
2    Sophie
Name: Nom, dtype: object

In [ ]:
# Extraire un sous-dataframe

sub_df = df[['Nom', 'Age']]

sub_df

      Nom  Age
0   Alice   39
1     Bob   42
2  Sophie   25

In [ ]:
# Affichier les deux premières lignes

df.head(2)

     Nom  Age  Ville
0  Alice   39   Lyon
1    Bob   42  Paris

In [ ]:
# Afficher les deux dernières lignes

df.tail(2)

      Nom  Age  Ville
1     Bob   42  Paris
2  Sophie   25   Lyon

In [ ]:
# Afficher la première ligne

df.iloc[0]

Nom      Alice
Age         39
Ville     Lyon
Name: 0, dtype: object

In [ ]:
# Afficher les lignes où l'âge est supérieur à 30 ans

df[df['Age'] > 30]

     Nom  Age  Ville
0  Alice   39   Lyon
1    Bob   42  Paris

In [ ]:
# Afficher les lignes où Ville est Lyon

df[df['Ville'] == "Lyon"]

      Nom  Age Ville
0   Alice   39  Lyon
2  Sophie   25  Lyon

In [ ]:
# Créer une copie de df
df_copie = df.copy()

# Enlever la colonne Ville de df_copie

df_copie.drop(columns=['Ville'], inplace=True)

In [ ]:
df_copie

      Nom  Age
0   Alice   39
1     Bob   42
2  Sophie   25

In [ ]:
df

      Nom  Age  Ville
0   Alice   39   Lyon
1     Bob   42  Paris
2  Sophie   25   Lyon

In [ ]:
# Sauvegarder df sous format csv

df.to_csv('Mes_donnees.csv')